import XCTest
@testable import NotchClipCore
import Foundation
import AppKit

final class CoreTests: XCTestCase {

    // MARK: - Classification

    func testClassifyPlainText() {
        let parser = PasteboardParser()
        let reps = [
            ParsedRepresentation(
                typeIdentifier: ClipboardTypeIdentifiers.utf8PlainText,
                data: Data("hello".utf8)
            )
        ]
        XCTAssertEqual(parser.classify(representations: reps), .plainText)
    }

    func testClassifyImage() {
        let parser = PasteboardParser()
        let reps = [
            ParsedRepresentation(typeIdentifier: ClipboardTypeIdentifiers.png, data: Data([0x89, 0x50]))
        ]
        XCTAssertEqual(parser.classify(representations: reps), .image)
    }

    func testClassifyTIFF() {
        let parser = PasteboardParser()
        let reps = [
            ParsedRepresentation(typeIdentifier: ClipboardTypeIdentifiers.tiff, data: Data([0x49, 0x49]))
        ]
        XCTAssertEqual(parser.classify(representations: reps), .image)
    }

    func testClassifyFileList() {
        let parser = PasteboardParser()
        let reps = [
            ParsedRepresentation(
                typeIdentifier: ClipboardTypeIdentifiers.fileURL,
                data: Data(),
                originalFilePath: "/tmp/a.txt"
            )
        ]
        XCTAssertEqual(parser.classify(representations: reps, filePaths: ["/tmp/a.txt"]), .fileList)
    }

    func testClassifyURL() {
        let parser = PasteboardParser()
        let reps = [
            ParsedRepresentation(
                typeIdentifier: ClipboardTypeIdentifiers.url,
                data: Data("https://example.com".utf8)
            )
        ]
        XCTAssertEqual(parser.classify(representations: reps), .url)
    }

    func testClassifyExactPlainTextWebURLAsURL() {
        let parser = PasteboardParser()
        let reps = [
            ParsedRepresentation(
                typeIdentifier: ClipboardTypeIdentifiers.utf8PlainText,
                data: Data("https://apps.apple.com/us/app/pages/id361309726".utf8)
            )
        ]
        XCTAssertEqual(parser.classify(representations: reps), .url)
    }

    func testDoesNotClassifyProseContainingURLAsURL() {
        let parser = PasteboardParser()
        let reps = [
            ParsedRepresentation(
                typeIdentifier: ClipboardTypeIdentifiers.utf8PlainText,
                data: Data("See https://apps.apple.com for details".utf8)
            )
        ]
        XCTAssertEqual(parser.classify(representations: reps), .plainText)
    }

    func testClassifyHTML() {
        let parser = PasteboardParser()
        let reps = [
            ParsedRepresentation(
                typeIdentifier: ClipboardTypeIdentifiers.html,
                data: Data("<b>x</b>".utf8)
            )
        ]
        XCTAssertEqual(parser.classify(representations: reps), .html)
    }

    func testClassifyRTF() {
        let parser = PasteboardParser()
        let reps = [
            ParsedRepresentation(
                typeIdentifier: ClipboardTypeIdentifiers.rtf,
                data: Data("{\\rtf1}".utf8)
            )
        ]
        XCTAssertEqual(parser.classify(representations: reps), .rtf)
    }

    // MARK: - Marker rejection

    func testRejectsTransientMarker() {
        let parser = PasteboardParser()
        XCTAssertTrue(parser.shouldReject(types: [
            ClipboardTypeIdentifiers.utf8PlainText,
            PasteboardMarkerTypes.transient
        ]))
    }

    func testRejectsConcealedMarker() {
        let parser = PasteboardParser()
        XCTAssertTrue(parser.shouldReject(types: [PasteboardMarkerTypes.concealed]))
    }

    func testRejectsAutoGeneratedMarker() {
        let parser = PasteboardParser()
        XCTAssertTrue(parser.shouldReject(types: [PasteboardMarkerTypes.autoGenerated]))
    }

    func testAcceptsNormalTypes() {
        let parser = PasteboardParser()
        XCTAssertFalse(parser.shouldReject(types: [
            ClipboardTypeIdentifiers.utf8PlainText,
            ClipboardTypeIdentifiers.png
        ]))
    }

    // MARK: - Fingerprint / dedupe

    func testFingerprintStableAndOrderIndependentWithinItem() {
        let a = ParsedRepresentation(itemIndex: 0, typeIdentifier: "public.utf8-plain-text", data: Data("hi".utf8))
        let b = ParsedRepresentation(itemIndex: 0, typeIdentifier: "public.png", data: Data([1, 2, 3]))
        let f1 = Fingerprinter.fingerprint(representations: [a, b])
        let f2 = Fingerprinter.fingerprint(representations: [b, a])
        XCTAssertEqual(f1, f2)
        XCTAssertEqual(f1.count, 64)
    }

    func testFingerprintDiffersForContent() {
        let f1 = Fingerprinter.fingerprint(typeIdentifier: "t", data: Data("a".utf8))
        let f2 = Fingerprinter.fingerprint(typeIdentifier: "t", data: Data("b".utf8))
        XCTAssertNotEqual(f1, f2)
    }

    func testFingerprintIncludesItemIndex() {
        let sameData = Data("x".utf8)
        let oneItem = [
            ParsedRepresentation(itemIndex: 0, typeIdentifier: "public.utf8-plain-text", data: sameData)
        ]
        let twoItems = [
            ParsedRepresentation(itemIndex: 0, typeIdentifier: "public.utf8-plain-text", data: sameData),
            ParsedRepresentation(itemIndex: 1, typeIdentifier: "public.utf8-plain-text", data: sameData)
        ]
        XCTAssertNotEqual(
            Fingerprinter.fingerprint(representations: oneItem),
            Fingerprinter.fingerprint(representations: twoItems)
        )
        // Order of hashing is by item index — deterministic for multi same-UTI
        let swappedInput = [
            ParsedRepresentation(itemIndex: 1, typeIdentifier: "public.utf8-plain-text", data: sameData),
            ParsedRepresentation(itemIndex: 0, typeIdentifier: "public.utf8-plain-text", data: sameData)
        ]
        XCTAssertEqual(
            Fingerprinter.fingerprint(representations: twoItems),
            Fingerprinter.fingerprint(representations: swappedInput)
        )
    }

    func testDedupeUpdatesRecency() throws {
        let repo = InMemoryClipboardRepository()
        let store = InMemoryPayloadStore()
        let engine = ClipboardEngine(repository: repo, payloadStore: store)

        let parsed = makeTextItem("dedupe-me")
        let r1 = engine.ingest(parsed: parsed)
        guard case .inserted(let first) = r1 else {
            return XCTFail("expected insert")
        }
        let created = first.createdAt

        Thread.sleep(forTimeInterval: 0.02)
        let r2 = engine.ingest(parsed: parsed)
        guard case .updatedExisting(let second) = r2 else {
            return XCTFail("expected update")
        }
        XCTAssertEqual(second.id, first.id)
        XCTAssertEqual(second.createdAt, created)
        XCTAssertGreaterThanOrEqual(second.updatedAt, first.updatedAt)
        XCTAssertEqual(try repo.allEntries().count, 1)
    }

    // MARK: - Persistence / pinned sorting

    func testPersistentRepositoryRoundTrip() throws {
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: dir) }
        let repo = try PersistentClipboardRepository(directory: dir)
        let entry = ClipboardEntry(
            primaryKind: .plainText,
            previewText: "p",
            searchText: "p",
            fingerprint: "abc"
        )
        try repo.upsert(entry)
        let repo2 = try PersistentClipboardRepository(directory: dir)
        let loaded = try repo2.entry(id: entry.id)
        XCTAssertEqual(loaded, entry)
    }

    func testPersistentRepositoryPreservesSubsecondTimestamps() throws {
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: dir) }
        let repo = try PersistentClipboardRepository(directory: dir)

        let created = Date(timeIntervalSinceReferenceDate: 700_000_000.123456789)
        let updated = Date(timeIntervalSinceReferenceDate: 700_000_001.987654321)
        let entry = ClipboardEntry(
            createdAt: created,
            updatedAt: updated,
            primaryKind: .plainText,
            previewText: "subsec",
            searchText: "subsec",
            fingerprint: "subsec-fp"
        )
        try repo.upsert(entry)

        let reloaded = try PersistentClipboardRepository(directory: dir)
        let loaded = try reloaded.entry(id: entry.id)
        XCTAssertEqual(loaded, entry)
        XCTAssertEqual(loaded?.createdAt.timeIntervalSinceReferenceDate, created.timeIntervalSinceReferenceDate)
        XCTAssertEqual(loaded?.updatedAt.timeIntervalSinceReferenceDate, updated.timeIntervalSinceReferenceDate)
    }

    func testPersistentRepositoryDecodesLegacyISO8601Dates() throws {
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: dir) }
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

        let id = UUID()
        let json = """
        {"entries":[{
          "id":"\(id.uuidString)",
          "createdAt":"2024-06-15T12:34:56Z",
          "updatedAt":"2024-06-15T12:34:56.500Z",
          "isPinned":false,
          "source":{"applicationName":null,"bundleIdentifier":null},
          "primaryKind":"plainText",
          "previewText":"legacy",
          "searchText":"legacy",
          "fingerprint":"legacy-fp",
          "payloadRefs":[]
        }]}
        """
        try Data(json.utf8).write(to: dir.appendingPathComponent("history.json"))

        let repo = try PersistentClipboardRepository(directory: dir)
        let loaded = try repo.entry(id: id)
        XCTAssertNotNil(loaded)
        XCTAssertEqual(loaded?.previewText, "legacy")
        XCTAssertEqual(loaded?.fingerprint, "legacy-fp")

        if let entry = loaded {
            try repo.upsert(entry)
        }
        let again = try PersistentClipboardRepository(directory: dir)
        XCTAssertEqual(try again.entry(id: id)?.fingerprint, "legacy-fp")
    }

    func testPersistentRepositoryMalformedHistoryThrows() throws {
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: dir) }
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        try Data("{not-valid-json".utf8).write(to: dir.appendingPathComponent("history.json"))

        let repo = try PersistentClipboardRepository(directory: dir)
        XCTAssertThrowsError(try repo.allEntries()) { error in
            XCTAssertEqual(error as? ClipboardRepositoryError, .persistenceFailed)
        }
    }

    func testPinnedFirstSorting() throws {
        let repo = InMemoryClipboardRepository()
        let older = ClipboardEntry(
            createdAt: Date(timeIntervalSince1970: 1),
            updatedAt: Date(timeIntervalSince1970: 10),
            isPinned: false,
            primaryKind: .plainText,
            previewText: "a",
            searchText: "a",
            fingerprint: "1"
        )
        let newer = ClipboardEntry(
            createdAt: Date(timeIntervalSince1970: 2),
            updatedAt: Date(timeIntervalSince1970: 20),
            isPinned: false,
            primaryKind: .plainText,
            previewText: "b",
            searchText: "b",
            fingerprint: "2"
        )
        let pinned = ClipboardEntry(
            createdAt: Date(timeIntervalSince1970: 3),
            updatedAt: Date(timeIntervalSince1970: 5),
            isPinned: true,
            primaryKind: .plainText,
            previewText: "c",
            searchText: "c",
            fingerprint: "3"
        )
        try repo.upsert(older)
        try repo.upsert(newer)
        try repo.upsert(pinned)
        let sorted = try repo.sortedEntries()
        XCTAssertEqual(sorted.map(\.fingerprint), ["3", "2", "1"])
    }

    func testPinReorderViaEngine() throws {
        let store = InMemoryPayloadStore()
        let repo = InMemoryClipboardRepository()
        let engine = ClipboardEngine(repository: repo, payloadStore: store)

        let a = engine.ingest(parsed: makeTextItem("alpha"))
        let b = engine.ingest(parsed: makeTextItem("beta"))
        guard case .inserted(let ea) = a, case .inserted = b else {
            return XCTFail("inserts")
        }
        try engine.setPinned(id: ea.id, isPinned: true)
        let sorted = try engine.sortedEntries()
        XCTAssertEqual(sorted.first?.id, ea.id)
        XCTAssertTrue(sorted.first?.isPinned == true)
    }

    // MARK: - Write-back / multi-item fidelity

    func testWriteBackPreservesRepresentations() throws {
        let store = InMemoryPayloadStore()
        let repo = InMemoryClipboardRepository()
        let pb = uniquePasteboard()
        let engine = ClipboardEngine(repository: repo, payloadStore: store)

        let textData = Data("write-back-payload".utf8)
        let typeID = ClipboardTypeIdentifiers.utf8PlainText
        let parsed = ParsedPasteboardItem(
            representations: [
                ParsedRepresentation(itemIndex: 0, typeIdentifier: typeID, data: textData)
            ],
            primaryKind: .plainText,
            previewText: "write-back-payload",
            searchText: "write-back-payload",
            fingerprint: Fingerprinter.fingerprint(typeIdentifier: typeID, data: textData)
        )
        guard case .inserted(let entry) = engine.ingest(parsed: parsed) else {
            return XCTFail("insert")
        }

        let written = try engine.paste(entry: entry, pasteboard: pb)
        XCTAssertGreaterThan(written, 0)
        let round = pb.data(forType: NSPasteboard.PasteboardType(typeID))
        XCTAssertEqual(round, textData)

        let result = engine.capture(from: pb)
        XCTAssertEqual(result, .ignoredSelfWrite)
    }

    func testTwoFilePasteboardRoundTrip() throws {
        let tmp = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        try FileManager.default.createDirectory(at: tmp, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmp) }

        let fileA = tmp.appendingPathComponent("a.txt")
        let fileB = tmp.appendingPathComponent("b.txt")
        let contentA = Data("file-a-bytes".utf8)
        let contentB = Data("file-b-bytes".utf8)
        try contentA.write(to: fileA)
        try contentB.write(to: fileB)

        let sourcePB = uniquePasteboard()
        let itemA = NSPasteboardItem()
        itemA.setString(fileA.absoluteString, forType: .fileURL)
        let itemB = NSPasteboardItem()
        itemB.setString(fileB.absoluteString, forType: .fileURL)
        sourcePB.clearContents()
        XCTAssertTrue(sourcePB.writeObjects([itemA, itemB]))
        XCTAssertEqual(sourcePB.pasteboardItems?.count, 2)

        let storeDir = tmp.appendingPathComponent("payloads", isDirectory: true)
        let store = try PayloadStore(rootDirectory: storeDir)
        let repo = InMemoryClipboardRepository()
        let engine = ClipboardEngine(repository: repo, payloadStore: store)
        let parser = PasteboardParser()

        guard let parsed = parser.parse(pasteboard: sourcePB) else {
            return XCTFail("parse two files")
        }
        XCTAssertEqual(parsed.primaryKind, .fileList)
        let fileReps = parsed.representations.filter { $0.typeIdentifier == ClipboardTypeIdentifiers.fileURL }
        XCTAssertEqual(fileReps.count, 2)
        XCTAssertEqual(fileReps.map(\.itemIndex), [0, 1])
        XCTAssertEqual(Set(fileReps.compactMap(\.originalFilePath)), Set([fileA.path, fileB.path]))

        // Stored payloads must not contain source file *contents* — only file-url representation bytes.
        guard case .inserted(let entry) = engine.ingest(parsed: parsed) else {
            return XCTFail("insert")
        }
        for ref in entry.payloadRefs {
            let data = try store.loadData(for: ref)
            XCTAssertNotEqual(data, contentA)
            XCTAssertNotEqual(data, contentB)
        }

        let destPB = uniquePasteboard()
        let written = try engine.paste(entry: entry, pasteboard: destPB)
        XCTAssertEqual(written, 2)
        XCTAssertEqual(destPB.pasteboardItems?.count, 2)

        let destItems = destPB.pasteboardItems ?? []
        let destPaths = destItems.compactMap { item -> String? in
            guard let data = item.data(forType: .fileURL) else { return nil }
            return parser.filePath(fromFileURLData: data)
        }
        XCTAssertEqual(destPaths, [fileA.path, fileB.path])
    }

    func testMultiItemSameUTIRoundTripAndFingerprint() throws {
        let pb = uniquePasteboard()
        let type = ClipboardTypeIdentifiers.utf8PlainText
        let d0 = Data("first".utf8)
        let d1 = Data("second".utf8)
        let i0 = NSPasteboardItem()
        i0.setData(d0, forType: NSPasteboard.PasteboardType(type))
        let i1 = NSPasteboardItem()
        i1.setData(d1, forType: NSPasteboard.PasteboardType(type))
        pb.clearContents()
        XCTAssertTrue(pb.writeObjects([i0, i1]))

        let parser = PasteboardParser()
        guard let parsed = parser.parse(pasteboard: pb) else {
            return XCTFail("parse")
        }
        XCTAssertEqual(parsed.representations.count, 2)
        XCTAssertEqual(parsed.representations.map(\.itemIndex), [0, 1])
        XCTAssertEqual(parsed.representations.map(\.typeIdentifier), [type, type])

        let store = InMemoryPayloadStore()
        let repo = InMemoryClipboardRepository()
        let engine = ClipboardEngine(repository: repo, payloadStore: store)
        guard case .inserted(let entry) = engine.ingest(parsed: parsed) else {
            return XCTFail("insert")
        }
        XCTAssertEqual(entry.fingerprint, Fingerprinter.fingerprint(representations: parsed.representations))

        let dest = uniquePasteboard()
        XCTAssertEqual(try engine.paste(entry: entry, pasteboard: dest), 2)
        let items = dest.pasteboardItems ?? []
        XCTAssertEqual(items.count, 2)
        XCTAssertEqual(items[0].data(forType: NSPasteboard.PasteboardType(type)), d0)
        XCTAssertEqual(items[1].data(forType: NSPasteboard.PasteboardType(type)), d1)
    }

    func testPlainAndRTFSameItemRoundTrip() throws {
        let text = "Hello rich"
        let plain = Data(text.utf8)
        let rtf = Data("{\\rtf1\\ansi \(text)}".utf8)
        let item = NSPasteboardItem()
        item.setData(plain, forType: NSPasteboard.PasteboardType(ClipboardTypeIdentifiers.utf8PlainText))
        item.setData(rtf, forType: NSPasteboard.PasteboardType(ClipboardTypeIdentifiers.rtf))
        let pb = uniquePasteboard()
        pb.clearContents()
        XCTAssertTrue(pb.writeObjects([item]))

        let parser = PasteboardParser()
        guard let parsed = parser.parse(pasteboard: pb) else {
            return XCTFail("parse")
        }
        let types = Set(parsed.representations.map(\.typeIdentifier))
        XCTAssertTrue(types.contains(ClipboardTypeIdentifiers.utf8PlainText) || types.contains(ClipboardTypeIdentifiers.plainText))
        XCTAssertTrue(types.contains(ClipboardTypeIdentifiers.rtf))
        XCTAssertTrue(parsed.representations.allSatisfy { $0.itemIndex == 0 })

        let store = InMemoryPayloadStore()
        let engine = ClipboardEngine(repository: InMemoryClipboardRepository(), payloadStore: store)
        guard case .inserted(let entry) = engine.ingest(parsed: parsed) else {
            return XCTFail("insert")
        }
        let dest = uniquePasteboard()
        XCTAssertEqual(try engine.paste(entry: entry, pasteboard: dest), 1)
        let destItem = dest.pasteboardItems?.first
        XCTAssertNotNil(destItem?.data(forType: NSPasteboard.PasteboardType(ClipboardTypeIdentifiers.rtf)))
        let plainOut = destItem?.data(forType: NSPasteboard.PasteboardType(ClipboardTypeIdentifiers.utf8PlainText))
            ?? destItem?.data(forType: .string)
        XCTAssertNotNil(plainOut)
    }

    func testOversizedRepresentationSkippedWholeNeverTruncated() throws {
        let cap = 64
        let parser = PasteboardParser(maxRepresentationBytes: cap)
        let over = Data(repeating: 0x41, count: cap + 1)
        let ok = Data("fits".utf8)

        let item = NSPasteboardItem()
        item.setData(over, forType: NSPasteboard.PasteboardType(ClipboardTypeIdentifiers.png))
        item.setData(ok, forType: NSPasteboard.PasteboardType(ClipboardTypeIdentifiers.utf8PlainText))
        let pb = uniquePasteboard()
        pb.clearContents()
        XCTAssertTrue(pb.writeObjects([item]))

        guard let parsed = parser.parse(pasteboard: pb) else {
            return XCTFail("parse should keep under-cap rep")
        }
        XCTAssertFalse(parsed.representations.contains { $0.typeIdentifier == ClipboardTypeIdentifiers.png })
        guard let textRep = parsed.representations.first(where: {
            $0.typeIdentifier == ClipboardTypeIdentifiers.utf8PlainText
                || $0.typeIdentifier == ClipboardTypeIdentifiers.plainText
        }) else {
            return XCTFail("plain text should remain")
        }
        XCTAssertEqual(textRep.data, ok)
        // Ensure we never stored a truncated PNG of length == cap under the PNG UTI.
        XCTAssertFalse(parsed.representations.contains {
            $0.typeIdentifier == ClipboardTypeIdentifiers.png && $0.data.count == cap
        })
    }

    func testSelfWriteIgnoredOnceThenExternalIdenticalCopyCaptured() throws {
        let store = InMemoryPayloadStore()
        let repo = InMemoryClipboardRepository()
        let engine = ClipboardEngine(repository: repo, payloadStore: store)
        let pb = uniquePasteboard()

        let textData = Data("identical-content".utf8)
        let typeID = ClipboardTypeIdentifiers.utf8PlainText
        let parsed = ParsedPasteboardItem(
            representations: [
                ParsedRepresentation(itemIndex: 0, typeIdentifier: typeID, data: textData)
            ],
            primaryKind: .plainText,
            previewText: "identical-content",
            searchText: "identical-content",
            fingerprint: Fingerprinter.fingerprint(typeIdentifier: typeID, data: textData)
        )
        guard case .inserted(let entry) = engine.ingest(parsed: parsed) else {
            return XCTFail("insert")
        }

        XCTAssertEqual(try engine.paste(entry: entry, pasteboard: pb), 1)
        XCTAssertEqual(engine.capture(from: pb), .ignoredSelfWrite)

        // External copy of the same content (new change count) must not be suppressed.
        // Re-write via a separate pasteboard write to bump change count.
        let external = NSPasteboardItem()
        external.setData(textData, forType: NSPasteboard.PasteboardType(typeID))
        pb.clearContents()
        XCTAssertTrue(pb.writeObjects([external]))

        let result = engine.capture(from: pb)
        guard case .updatedExisting(let updated) = result else {
            return XCTFail("expected dedupe update after external identical copy, got \(result)")
        }
        XCTAssertEqual(updated.id, entry.id)
        XCTAssertEqual(try repo.allEntries().count, 1)
    }

    func testZeroWriteLeavesNoSuppression() throws {
        let engine = ClipboardEngine(
            repository: InMemoryClipboardRepository(),
            payloadStore: InMemoryPayloadStore()
        )
        let pb = uniquePasteboard()
        // Entry with no loadable payload refs → zero write
        let empty = ClipboardEntry(
            primaryKind: .plainText,
            previewText: "x",
            searchText: "x",
            fingerprint: "empty-fp",
            payloadRefs: [
                PayloadReference(
                    itemIndex: 0,
                    typeIdentifier: ClipboardTypeIdentifiers.utf8PlainText,
                    relativePath: "",
                    byteCount: 0
                )
            ]
        )
        XCTAssertEqual(try engine.paste(entry: empty, pasteboard: pb), 0)

        let item = NSPasteboardItem()
        item.setString("after-failed-write", forType: .string)
        pb.clearContents()
        XCTAssertTrue(pb.writeObjects([item]))
        let result = engine.capture(from: pb)
        if case .ignoredSelfWrite = result {
            XCTFail("failed write must not suppress subsequent captures")
        }
    }

    func testPayloadReferenceDecodesMissingItemIndexAsZero() throws {
        let id = UUID()
        let json = """
        {
          "id":"\(id.uuidString)",
          "typeIdentifier":"public.utf8-plain-text",
          "relativePath":"\(id.uuidString)/payload",
          "byteCount":4,
          "originalFilePath":null
        }
        """
        let ref = try JSONDecoder().decode(PayloadReference.self, from: Data(json.utf8))
        XCTAssertEqual(ref.itemIndex, 0)
        XCTAssertEqual(ref.typeIdentifier, "public.utf8-plain-text")
        XCTAssertEqual(ref.byteCount, 4)
    }

    // MARK: - Search

    func testLocalSearch() throws {
        let repo = InMemoryClipboardRepository()
        try repo.upsert(
            ClipboardEntry(
                primaryKind: .plainText,
                previewText: "Hello World",
                searchText: "hello world",
                fingerprint: "1"
            )
        )
        try repo.upsert(
            ClipboardEntry(
                primaryKind: .plainText,
                previewText: "Swift Package",
                searchText: "swift package",
                fingerprint: "2"
            )
        )
        let hits = try repo.search(query: "SWIFT")
        XCTAssertEqual(hits.count, 1)
        XCTAssertEqual(hits.first?.fingerprint, "2")
    }

    // MARK: - Missing files

    func testMissingFileDetection() {
        let missing = "/tmp/notchclip-definitely-missing-\(UUID().uuidString)"
        let entry = ClipboardEntry(
            primaryKind: .fileList,
            previewText: "x",
            searchText: missing.lowercased(),
            fingerprint: "f",
            payloadRefs: [
                PayloadReference(
                    typeIdentifier: ClipboardTypeIdentifiers.fileURL,
                    relativePath: "",
                    byteCount: 0,
                    originalFilePath: missing
                )
            ]
        )
        XCTAssertTrue(entry.hasMissingFiles())
    }

    func testPresentFileNotMissing() throws {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try Data("x".utf8).write(to: url)
        defer { try? FileManager.default.removeItem(at: url) }
        let entry = ClipboardEntry(
            primaryKind: .fileList,
            previewText: "x",
            searchText: url.path.lowercased(),
            fingerprint: "f",
            payloadRefs: [
                PayloadReference(
                    typeIdentifier: ClipboardTypeIdentifiers.fileURL,
                    relativePath: "",
                    byteCount: 0,
                    originalFilePath: url.path
                )
            ]
        )
        XCTAssertFalse(entry.hasMissingFiles())
    }

    // MARK: - Presentation generation guard

    func testPresentationGenerationStaleDismiss() {
        var gen = PresentationGeneration()
        let t1 = gen.beginPresentation()
        XCTAssertTrue(gen.isCurrent(t1))
        let t2 = gen.beginPresentation()
        XCTAssertFalse(gen.isCurrent(t1))
        XCTAssertTrue(gen.isCurrent(t2))
        XCTAssertFalse(gen.dismissIfCurrent(t1))
        XCTAssertTrue(gen.dismissIfCurrent(t2))
        XCTAssertFalse(gen.isCurrent(t2))
    }

    // MARK: - Motion policy

    func testMotionPolicyReduceMotionIsFadeOnly() {
        XCTAssertEqual(MotionPolicy.behavior(reduceMotion: true), .fadeOnly)
        XCTAssertEqual(MotionPolicy.behavior(reduceMotion: false), .full)
        XCTAssertEqual(
            MotionPolicy.behavior(for: MotionPreferences(reduceMotion: true)),
            .fadeOnly
        )
    }

    // MARK: - Atomic payload storage

    func testPayloadStoreAtomicRoundTrip() throws {
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: dir) }
        let store = try PayloadStore(rootDirectory: dir)
        let id = UUID()
        let data = Data("payload-bytes".utf8)
        let rep = ParsedRepresentation(
            itemIndex: 0,
            typeIdentifier: "public.utf8-plain-text",
            data: data
        )
        let ref = try store.store(entryID: id, representation: rep)
        XCTAssertEqual(try store.loadData(for: ref), data)
        XCTAssertEqual(ref.itemIndex, 0)
        let url = store.rootDirectory.appendingPathComponent(ref.relativePath)
        XCTAssertTrue(FileManager.default.fileExists(atPath: url.path))
    }

    // MARK: - Monitor pause

    @MainActor
    func testMonitorPauseAndResume() {
        let store = InMemoryPayloadStore()
        let repo = InMemoryClipboardRepository()
        let engine = ClipboardEngine(repository: repo, payloadStore: store)
        let pb = uniquePasteboard()
        let monitor = ClipboardMonitor(engine: engine, pasteboard: pb, pollInterval: 60)
        monitor.start()
        monitor.pause()
        XCTAssertTrue(monitor.isPaused)
        monitor.resume()
        XCTAssertFalse(monitor.isPaused)
        monitor.stop()
    }

    // MARK: - Reliability: failures, consistency, concurrency

    func testRepositoryFailureAfterPayloadStoreReturnsFailedAndCleansPayloads() throws {
        let store = InMemoryPayloadStore()
        let repo = FailingClipboardRepository(failOnUpsertCount: 1)
        let engine = ClipboardEngine(repository: repo, payloadStore: store)
        let parsed = makeTextItem("repo-fail-after-payload")

        let result = engine.ingest(parsed: parsed)
        guard case .failed(let failure) = result else {
            return XCTFail("expected .failed, got \(result)")
        }
        if case .repository = failure {
            // ok
        } else {
            XCTFail("expected repository failure, got \(failure)")
        }
        XCTAssertEqual(try store.storedEntryIDs().count, 0)
        XCTAssertEqual(try repo.allEntries().count, 0)
    }

    func testMidBatchPayloadFailureLeavesNoPartialEntry() throws {
        let store = InMemoryPayloadStore()
        store.failOnRepresentationIndex = 2
        let repo = InMemoryClipboardRepository()
        let engine = ClipboardEngine(repository: repo, payloadStore: store)

        let reps = [
            ParsedRepresentation(itemIndex: 0, typeIdentifier: "public.utf8-plain-text", data: Data("a".utf8)),
            ParsedRepresentation(itemIndex: 1, typeIdentifier: "public.utf8-plain-text", data: Data("b".utf8))
        ]
        let parsed = ParsedPasteboardItem(
            representations: reps,
            primaryKind: .plainText,
            previewText: "multi",
            searchText: "multi",
            fingerprint: Fingerprinter.fingerprint(representations: reps)
        )

        let result = engine.ingest(parsed: parsed)
        guard case .failed(let failure) = result else {
            return XCTFail("expected .failed, got \(result)")
        }
        if case .payload = failure {
            // ok
        } else {
            XCTFail("expected payload failure, got \(failure)")
        }
        XCTAssertEqual(try repo.allEntries().count, 0)
        XCTAssertEqual(try store.storedEntryIDs().count, 0)
        XCTAssertEqual(try store.totalByteCount(), 0)
    }

    func testDiskPayloadStoreMidBatchFailureLeavesNoFinalDirectory() throws {
        // Use a real PayloadStore with an unwritable staging path after creating root —
        // inject failure by using a subclass pattern: write one rep then make parent read-only is flaky.
        // Instead: storeAll to a path, then verify transactional API via InMemory above and
        // that PayloadStore.storeAll cleans staging on throw by using empty write to invalid UTF8 name —
        // simplest: call storeAll with representations and delete mid via failing FS isn't portable.
        // Verify publish semantics: successful storeAll creates exactly one entry dir.
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: dir) }
        let store = try PayloadStore(rootDirectory: dir)
        let id = UUID()
        let refs = try store.storeAll(
            entryID: id,
            representations: [
                ParsedRepresentation(itemIndex: 0, typeIdentifier: "t", data: Data("x".utf8)),
                ParsedRepresentation(itemIndex: 1, typeIdentifier: "t", data: Data("y".utf8))
            ]
        )
        XCTAssertEqual(refs.count, 2)
        XCTAssertTrue(store.entryDirectoryExists(entryID: id))
        // No leftover staging dirs
        let contents = try FileManager.default.contentsOfDirectory(atPath: dir.path)
        XCTAssertFalse(contents.contains { $0.contains("staging") })
    }

    func testDeleteRepositoryFailureLeavesPayloadsIntact() throws {
        let store = InMemoryPayloadStore()
        let repo = FailingClipboardRepository()
        let engine = ClipboardEngine(repository: repo, payloadStore: store)
        let parsed = makeTextItem("delete-fail")
        guard case .inserted(let entry) = engine.ingest(parsed: parsed) else {
            return XCTFail("insert")
        }
        XCTAssertTrue(store.entryDirectoryExists(entryID: entry.id))

        repo.failOnRemoveCount = 1
        XCTAssertThrowsError(try engine.delete(id: entry.id))
        // Metadata still present (remove failed), payloads intact — not a broken row without payloads.
        XCTAssertNotNil(try repo.entry(id: entry.id))
        XCTAssertTrue(store.entryDirectoryExists(entryID: entry.id))
    }

    func testConcurrentSameFingerprintIngestsResultInOneEntry() throws {
        let store = InMemoryPayloadStore()
        let repo = InMemoryClipboardRepository()
        let engine = ClipboardEngine(repository: repo, payloadStore: store)
        let parsed = makeTextItem("concurrent-dup-\(UUID().uuidString)")

        let group = DispatchGroup()
        var results: [CaptureResult] = []
        let resultsLock = NSLock()
        for _ in 0..<8 {
            group.enter()
            DispatchQueue.global().async {
                let r = engine.ingest(parsed: parsed)
                resultsLock.lock()
                results.append(r)
                resultsLock.unlock()
                group.leave()
            }
        }
        XCTAssertEqual(group.wait(timeout: .now() + 5), .success)
        XCTAssertEqual(try repo.allEntries().count, 1)
        let inserts = results.filter {
            if case .inserted = $0 { return true }
            return false
        }
        let updates = results.filter {
            if case .updatedExisting = $0 { return true }
            return false
        }
        XCTAssertEqual(inserts.count, 1)
        XCTAssertEqual(updates.count, 7)
    }

    func testClearUnpinnedPreservesPinnedAndClearAllRemovesAll() throws {
        let store = InMemoryPayloadStore()
        let repo = InMemoryClipboardRepository()
        let engine = ClipboardEngine(repository: repo, payloadStore: store)

        guard case .inserted(let a) = engine.ingest(parsed: makeTextItem("clear-a")),
              case .inserted(let b) = engine.ingest(parsed: makeTextItem("clear-b")),
              case .inserted(let c) = engine.ingest(parsed: makeTextItem("clear-c")) else {
            return XCTFail("inserts")
        }
        try engine.setPinned(id: b.id, isPinned: true)

        try engine.clearUnpinned()
        let afterUnpinned = try engine.sortedEntries()
        XCTAssertEqual(afterUnpinned.count, 1)
        XCTAssertEqual(afterUnpinned.first?.id, b.id)
        XCTAssertFalse(store.entryDirectoryExists(entryID: a.id))
        XCTAssertTrue(store.entryDirectoryExists(entryID: b.id))
        XCTAssertFalse(store.entryDirectoryExists(entryID: c.id))

        try engine.clearAll()
        XCTAssertEqual(try engine.entryCount(), 0)
        XCTAssertEqual(try store.storedEntryIDs().count, 0)
        XCTAssertEqual(try engine.totalPayloadByteCount(), 0)
    }

    func testSourceProviderMetadataReachesCapturedEntry() throws {
        let expected = SourceMetadata(bundleIdentifier: "com.example.SourceApp", applicationName: "SourceApp")
        let engine = ClipboardEngine(
            repository: InMemoryClipboardRepository(),
            payloadStore: InMemoryPayloadStore(),
            sourceProvider: { expected }
        )
        let pb = uniquePasteboard()
        let item = NSPasteboardItem()
        item.setString("from-source-app", forType: .string)
        pb.clearContents()
        XCTAssertTrue(pb.writeObjects([item]))

        let result = engine.capture(from: pb)
        guard case .inserted(let entry) = result else {
            return XCTFail("expected insert, got \(result)")
        }
        XCTAssertEqual(entry.source, expected)
    }

    func testProductionStyleStorageInitFailureIsSurfaced() throws {
        // Unwritable path (file where a directory is required).
        let filePath = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try Data("not-a-dir".utf8).write(to: filePath)
        defer { try? FileManager.default.removeItem(at: filePath) }

        XCTAssertThrowsError(try PersistentClipboardRepository(directory: filePath))
        XCTAssertThrowsError(try PayloadStore(rootDirectory: filePath))
        // Production AppModel maps this to storageError and disables capture (no memory fallback).
    }

    func testOrphanPayloadCleanup() throws {
        let store = InMemoryPayloadStore()
        let repo = InMemoryClipboardRepository()
        let engine = ClipboardEngine(repository: repo, payloadStore: store)
        guard case .inserted(let entry) = engine.ingest(parsed: makeTextItem("orphan-seed")) else {
            return XCTFail("insert")
        }
        // Simulate orphan: payload for unknown ID
        let orphanID = UUID()
        _ = try store.storeAll(
            entryID: orphanID,
            representations: [
                ParsedRepresentation(itemIndex: 0, typeIdentifier: "t", data: Data("o".utf8))
            ]
        )
        XCTAssertTrue(store.entryDirectoryExists(entryID: orphanID))
        let removed = try engine.removeOrphanedPayloads()
        XCTAssertEqual(removed, 1)
        XCTAssertFalse(store.entryDirectoryExists(entryID: orphanID))
        XCTAssertTrue(store.entryDirectoryExists(entryID: entry.id))
    }

    // MARK: - Helpers

    private func uniquePasteboard() -> NSPasteboard {
        NSPasteboard(name: NSPasteboard.Name("NotchClipTests.\(UUID().uuidString)"))
    }

    private func makeTextItem(_ text: String) -> ParsedPasteboardItem {
        let data = Data(text.utf8)
        let typeID = ClipboardTypeIdentifiers.utf8PlainText
        return ParsedPasteboardItem(
            representations: [
                ParsedRepresentation(itemIndex: 0, typeIdentifier: typeID, data: data)
            ],
            primaryKind: .plainText,
            previewText: text,
            searchText: text.lowercased(),
            fingerprint: Fingerprinter.fingerprint(typeIdentifier: typeID, data: data)
        )
    }
}

// MARK: - Failure injection helpers (tests only)

/// Repository that can fail on upsert/remove for reliability tests.
final class FailingClipboardRepository: ClipboardRepository, @unchecked Sendable {
    private let inner = InMemoryClipboardRepository()
    private let lock = NSLock()
    var failOnUpsertCount: Int?
    var failOnRemoveCount: Int?
    private var upserts = 0
    private var removes = 0

    init(failOnUpsertCount: Int? = nil, failOnRemoveCount: Int? = nil) {
        self.failOnUpsertCount = failOnUpsertCount
        self.failOnRemoveCount = failOnRemoveCount
    }

    func allEntries() throws -> [ClipboardEntry] { try inner.allEntries() }
    func entry(id: UUID) throws -> ClipboardEntry? { try inner.entry(id: id) }
    func sortedEntries() throws -> [ClipboardEntry] { try inner.sortedEntries() }
    func search(query: String) throws -> [ClipboardEntry] { try inner.search(query: query) }
    func removeAll() throws { try inner.removeAll() }

    func upsert(_ entry: ClipboardEntry) throws {
        lock.lock()
        upserts += 1
        let n = upserts
        let failAt = failOnUpsertCount
        lock.unlock()
        if let failAt, n == failAt {
            throw ClipboardRepositoryError.persistenceFailed
        }
        try inner.upsert(entry)
    }

    func remove(id: UUID) throws {
        lock.lock()
        removes += 1
        let n = removes
        let failAt = failOnRemoveCount
        lock.unlock()
        if let failAt, n == failAt {
            throw ClipboardRepositoryError.persistenceFailed
        }
        try inner.remove(id: id)
    }
}
