import Foundation
import AppKit
import CryptoKit
import UniformTypeIdentifiers

/// Pasteboard type markers that must not be retained (nspasteboard.org convention).
public enum PasteboardMarkerTypes {
    public static let transient = "org.nspasteboard.TransientType"
    public static let concealed = "org.nspasteboard.ConcealedType"
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
    public static let source = "org.nspasteboard.Source"

    public static let rejected: Set<String> = [
        transient,
        concealed,
        autoGenerated
    ]
}

/// Well-known representation type identifiers we prioritize.
public enum ClipboardTypeIdentifiers {
    public static let plainText = UTType.plainText.identifier
    public static let utf8PlainText = "public.utf8-plain-text"
    public static let rtf = UTType.rtf.identifier
    public static let html = UTType.html.identifier
    public static let url = UTType.url.identifier
    public static let fileURL = UTType.fileURL.identifier
    public static let png = UTType.png.identifier
    public static let tiff = UTType.tiff.identifier
    public static let utf16External = "public.utf16-external-plain-text"

    public static let preferredOrder: [String] = [
        fileURL,
        png,
        tiff,
        url,
        html,
        rtf,
        plainText,
        utf8PlainText
    ]
}

/// Parses `NSPasteboard` contents into domain items with a whole-representation size cap.
///
/// **Cap policy (v1):** default `maxRepresentationBytes` is 64 MiB. A representation is kept
/// entirely when `data.count <= cap`, otherwise it is **skipped whole**. Bytes are never
/// truncated and re-labeled as the original UTI.
public struct PasteboardParser: Sendable {
    /// Maximum bytes retained per individual representation (default 64 MiB).
    public var maxRepresentationBytes: Int

    public static let defaultMaxRepresentationBytes = 64 * 1024 * 1024

    public init(maxRepresentationBytes: Int = PasteboardParser.defaultMaxRepresentationBytes) {
        self.maxRepresentationBytes = maxRepresentationBytes
    }

    public func shouldReject(types: [String]) -> Bool {
        !Set(types).isDisjoint(with: PasteboardMarkerTypes.rejected)
    }

    public func shouldReject(_ pasteboard: NSPasteboard) -> Bool {
        shouldReject(types: pasteboard.types?.map(\.rawValue) ?? [])
    }

    /// Parse a live pasteboard (tests / synchronous paths). Prefer `parse(snapshot:)` off-main.
    public func parse(
        pasteboard: NSPasteboard = .general,
        source: SourceMetadata = SourceMetadata()
    ) -> ParsedPasteboardItem? {
        let snap = PasteboardSnapshotter.snapshot(
            pasteboard: pasteboard,
            source: source,
            maxRepresentationBytes: maxRepresentationBytes
        )
        return parse(snapshot: snap)
    }

    /// Parse an immutable snapshot (background-safe: no live pasteboard, no HTML WebKit import).
    public func parse(snapshot: PasteboardSnapshot) -> ParsedPasteboardItem? {
        if shouldReject(types: snapshot.boardTypes) {
            return nil
        }
        for item in snapshot.items {
            if shouldReject(types: item.types) {
                return nil
            }
        }

        var representations: [ParsedRepresentation] = []
        var originalFilePaths: [String] = []

        for (itemIndex, item) in snapshot.items.enumerated() {
            // Preserve each source item's `types` order (deduplicated). Classification /
            // preview selection still use their own preference logic elsewhere.
            var seen = Set<String>()
            var orderedTypes: [String] = []
            for typeID in item.types {
                if seen.contains(typeID) { continue }
                seen.insert(typeID)
                orderedTypes.append(typeID)
            }

            for typeID in orderedTypes {
                if PasteboardMarkerTypes.rejected.contains(typeID) { continue }
                if typeID == PasteboardMarkerTypes.source { continue }
                guard let data = item.dataByType[typeID], !data.isEmpty else { continue }
                if data.count > maxRepresentationBytes { continue }

                var path: String?
                if typeID == ClipboardTypeIdentifiers.fileURL {
                    path = filePath(fromFileURLData: data)
                    if let path {
                        originalFilePaths.append(path)
                    }
                }

                representations.append(
                    ParsedRepresentation(
                        itemIndex: itemIndex,
                        typeIdentifier: typeID,
                        data: data,
                        originalFilePath: path
                    )
                )
            }
        }

        guard !representations.isEmpty else { return nil }

        let kind = classify(representations: representations, filePaths: originalFilePaths)
        let preview = makePreview(representations: representations, filePaths: originalFilePaths, kind: kind)
        let search = makeSearchText(representations: representations, filePaths: originalFilePaths)
        let fingerprint = Fingerprinter.fingerprint(representations: representations)

        return ParsedPasteboardItem(
            representations: representations,
            primaryKind: kind,
            previewText: preview,
            searchText: search,
            source: snapshot.source,
            fingerprint: fingerprint,
            originalFilePaths: originalFilePaths
        )
    }

    public func classify(
        representations: [ParsedRepresentation],
        filePaths: [String] = []
    ) -> ClipboardContentKind {
        let ids = Set(representations.map(\.typeIdentifier))
        let paths = filePaths.isEmpty
            ? representations.compactMap(\.originalFilePath)
            : filePaths
        let hasFiles = !paths.isEmpty || ids.contains(ClipboardTypeIdentifiers.fileURL)
        let hasImage = ids.contains(ClipboardTypeIdentifiers.png) || ids.contains(ClipboardTypeIdentifiers.tiff)
        let hasURL = ids.contains(ClipboardTypeIdentifiers.url)
        let hasHTML = ids.contains(ClipboardTypeIdentifiers.html)
        let hasRTF = ids.contains(ClipboardTypeIdentifiers.rtf)
        let hasText = ids.contains(ClipboardTypeIdentifiers.plainText)
            || ids.contains(ClipboardTypeIdentifiers.utf8PlainText)
            || ids.contains(ClipboardTypeIdentifiers.utf16External)

        var hits = 0
        if hasFiles { hits += 1 }
        if hasImage { hits += 1 }
        if hasURL { hits += 1 }
        if hasHTML || hasRTF || hasText { hits += 1 }

        if hits > 1 && (hasFiles || hasImage) { return .mixed }
        if hasFiles { return .fileList }
        if hasImage { return .image }
        if hasURL && !hasText && !hasHTML && !hasRTF { return .url }
        if hasHTML { return .html }
        if hasRTF { return .rtf }
        if hasURL { return .url }
        if hasText { return .plainText }
        return .other
    }

    // MARK: - Private

    /// Extract a filesystem path from retained `public.file-url` bytes (no source file I/O).
    public func filePath(fromFileURLData data: Data) -> String? {
        if let url = NSURL(absoluteURLWithDataRepresentation: data, relativeTo: nil) as URL?,
           url.isFileURL {
            return url.path
        }
        if let raw = String(data: data, encoding: .utf8)?
            .trimmingCharacters(in: CharacterSet(charactersIn: "\0"))
            .trimmingCharacters(in: .whitespacesAndNewlines),
           !raw.isEmpty {
            if let url = URL(string: raw), url.isFileURL {
                return url.path
            }
            if raw.hasPrefix("/") {
                return raw
            }
        }
        return nil
    }

    private func makePreview(
        representations: [ParsedRepresentation],
        filePaths: [String],
        kind: ClipboardContentKind
    ) -> String {
        let paths = filePaths.isEmpty
            ? representations.compactMap(\.originalFilePath)
            : filePaths
        switch kind {
        case .fileList:
            if paths.count == 1 {
                return (paths[0] as NSString).lastPathComponent
            }
            return "\(paths.count) files"
        case .image:
            return "Image"
        case .url:
            if let s = string(from: representations, types: [
                ClipboardTypeIdentifiers.url,
                ClipboardTypeIdentifiers.plainText,
                ClipboardTypeIdentifiers.utf8PlainText
            ]) {
                return String(s.prefix(200))
            }
            return "URL"
        case .html, .rtf, .plainText, .mixed, .other:
            if let s = string(from: representations, types: [
                ClipboardTypeIdentifiers.plainText,
                ClipboardTypeIdentifiers.utf8PlainText,
                ClipboardTypeIdentifiers.rtf,
                ClipboardTypeIdentifiers.html
            ]) {
                let collapsed = s
                    .replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
                    .trimmingCharacters(in: .whitespacesAndNewlines)
                return String(collapsed.prefix(200))
            }
            return kind.rawValue
        }
    }

    private func makeSearchText(
        representations: [ParsedRepresentation],
        filePaths: [String]
    ) -> String {
        let paths = filePaths.isEmpty
            ? representations.compactMap(\.originalFilePath)
            : filePaths
        var parts: [String] = paths
        if let s = string(from: representations, types: [
            ClipboardTypeIdentifiers.plainText,
            ClipboardTypeIdentifiers.utf8PlainText,
            ClipboardTypeIdentifiers.url,
            ClipboardTypeIdentifiers.html,
            ClipboardTypeIdentifiers.rtf
        ]) {
            parts.append(s)
        }
        return parts.joined(separator: "\n").lowercased()
    }

    private func string(from representations: [ParsedRepresentation], types: [String]) -> String? {
        for typeID in types {
            guard let rep = representations.first(where: { $0.typeIdentifier == typeID }) else { continue }
            if typeID == ClipboardTypeIdentifiers.rtf {
                // RTF → plain without HTML WebKit import (safe off-main for our usage).
                if let attr = NSAttributedString(rtf: rep.data, documentAttributes: nil) {
                    return attr.string
                }
                continue
            }
            if typeID == ClipboardTypeIdentifiers.html {
                // Never call NSAttributedString(html:) off-main — Apple requires main thread.
                return Self.plainTextFromHTML(rep.data)
            }
            if let s = String(data: rep.data, encoding: .utf8) { return s }
            if let s = String(data: rep.data, encoding: .utf16) { return s }
        }
        return nil
    }

    /// Background-safe HTML → preview text: UTF-8 decode, strip tags/entities (no WebKit).
    public static func plainTextFromHTML(_ data: Data) -> String? {
        guard var s = String(data: data, encoding: .utf8) ?? String(data: data, encoding: .utf16) else {
            return nil
        }
        s = s.replacingOccurrences(
            of: #"(?is)<(script|style)[^>]*>.*?</\1>"#,
            with: " ",
            options: .regularExpression
        )
        s = s.replacingOccurrences(of: #"<[^>]+>"#, with: " ", options: .regularExpression)
        let entities: [(String, String)] = [
            ("&nbsp;", " "), ("&amp;", "&"), ("&lt;", "<"), ("&gt;", ">"),
            ("&quot;", "\""), ("&#39;", "'"), ("&apos;", "'")
        ]
        for (entity, replacement) in entities {
            s = s.replacingOccurrences(of: entity, with: replacement)
        }
        s = s.replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return s.isEmpty ? nil : s
    }
}

/// SHA-256 fingerprinting of retained representations (stable across runs).
///
/// Framing: for each rep sorted by `(itemIndex, typeIdentifier, byteCount, data)`:
/// itemIndex (UInt32 BE) · type UTF-8 · `0` · byte length (UInt64 BE) · data · `0`.
public enum Fingerprinter {
    public static func fingerprint(representations: [ParsedRepresentation]) -> String {
        let sorted = representations.sorted { lhs, rhs in
            if lhs.itemIndex != rhs.itemIndex { return lhs.itemIndex < rhs.itemIndex }
            if lhs.typeIdentifier != rhs.typeIdentifier {
                return lhs.typeIdentifier < rhs.typeIdentifier
            }
            if lhs.data.count != rhs.data.count { return lhs.data.count < rhs.data.count }
            return lhs.data.lexicographicallyPrecedes(rhs.data)
        }
        var hasher = SHA256()
        for rep in sorted {
            var indexBE = UInt32(rep.itemIndex).bigEndian
            withUnsafeBytes(of: &indexBE) { hasher.update(bufferPointer: $0) }
            hasher.update(data: Data(rep.typeIdentifier.utf8))
            hasher.update(data: Data([0]))
            var lenBE = UInt64(rep.data.count).bigEndian
            withUnsafeBytes(of: &lenBE) { hasher.update(bufferPointer: $0) }
            hasher.update(data: rep.data)
            hasher.update(data: Data([0]))
        }
        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }

    public static func fingerprint(typeIdentifier: String, data: Data, itemIndex: Int = 0) -> String {
        fingerprint(representations: [
            ParsedRepresentation(itemIndex: itemIndex, typeIdentifier: typeIdentifier, data: data)
        ])
    }
}
